### ISSUE TITLE
로그인 성공한 후에 로그인이 되어있는 상태의 화면으로 redirect

### ISSUE THREAD

**Issue by ppakjae** [minkwns/project_selab#23]
현재는 로그인 성공한경우 res.redirect("/");이나 로그인 성공한 경우에는 로그인 링크가 로그 아웃으로 바뀌어야 하고 로그인 되어있는 상태의 새로운 화면으로 redirect 되어야함

**Comment by baezzys** [comment]
So we need to another new html file?
