### ISSUE TITLE
로그인 및 회원가입

### ISSUE THREAD

**Issue by KRCHOIJUNHO** [minkwns/project_selab#41]
1.  DB table column에 따라 변수이름 다 바꿔주기

2. 회원가입 
- user name 중복 확인 => 틀릴경우 경고창 
- user ID 중복 확인 => 틀릴경우 경고창
- password 와 password_confirm 이 같은지 확인 => 틀릴경우 경고창
- user ID 이메일 형식인지 확인

**Comment by ppakjae** [comment]
username은 동명이인이 존재하기 때문에 user_id만 중복확인하면 된다고 생각합니다.
